### ISSUE TITLE
How to play on web

### ISSUE THREAD

**Issue by anhlt309** [atyenoria/janus-webrtc-gateway-docker#4]
I have a nginx-rtmp server for streaming local video files and I can view on my android by app supports rtmp protocol. Now, I want to view those video files on web (by chrome or firefox...), so I found janus-webrtc-gateway. I had configured nginx.conf as you recommend, but I dont how to select and view those video file on web. Please help me, thank you.

**Comment by atyenoria** [comment]
The easiest way to play rtmp stream is using teh  rtmp player made by flash. But, I don't recommend, because flash seems to disappear. So, the recommended way to play hls or dash on web by using html 5 player. For this video.js is very easy for playing  on web (Chrome, Safari...etc ) as a test. The transcoding nginx config from rtmp to hls or dash is very common thing. No special knowledge is needed.  FYI, if you use react, it is tedious to play the hls stream because of no good library in my experience. you have to create it by yourself.
