### ISSUE TITLE
[transports/janus_http.c:janus_http_handler:1239] Invalid url /

### ISSUE THREAD

**Issue by json1994** [atyenoria/janus-webrtc-gateway-docker#48]
[transports/janus_http.c:janus_http_handler:1239] Invalid url / 
How to deal with this problem？

**Comment by maanas** [comment]
The server root (/janus by default, but configurable), which you only POST to in order to create a Janus session;

Ref: https://janus.conf.meetecho.com/docs/rest.html

**Comment by adiii717** [comment]
This is not an error and you can ignore this
Most probably this occurs when you call API endpoint with just `/` instead of `/janus/info` or any other invalid path will be printed in the logs.

To reproduce this error jus try this

```
curl https://janus.yourhost.com:8088/

```
you will see in the logs
```
[ERR] [transports/janus_http.c:janus_http_handler:1213] Invalid url /
```
While the correct to check the health of the instance should be

```
curl https://janus.yourhost.com:8088/janus/info
```
