### ISSUE TITLE
Recorded files on AWS S3?

### ISSUE THREAD

**Issue by anildigital** [atyenoria/janus-webrtc-gateway-docker#5]
Hi,

Storing recorded videos on AWS S3 and streaming those recordings with nginx-rtmp-module?

Basically, in our videoroom, each user can record his WebRTC session and a recording file (mp4?) should get generated and should be stored on S3. Other users should able to see this recording and should be able to play it with (nginx-rtmp-module streaming support)

Is this functionality possible (maybe by little customization) with this docker container?

Please let me know.

Thanks,
Anil

**Comment by atyenoria** [comment]
Probably, it it possible for you to do what you want to.
But, please explain more.  What is the streaming method from S3 recording mp4 file? Hls, Rtmp, Webrtc?
The simple solution is to create HLS Segmentation file from the mp4 file combined by janus-gateway by using ffmpeg, and set nginx-rtmp-module config, and play the video.js. 
The first step is ok for this. 
In order to do this dynamically, you should use http://www.meetecho.com/blog/event-handlers-a-practical-example .

**Comment by harshald28** [comment]
Hi,
I want to store video room recordings directly to AWS s3 (or google storage). So right now we can save locally by specifying location while creating a video room, but I want to store that recordings directly to cloud storage.

Please advice how to achieve this
Thanks in advance.
