### ISSUE TITLE
libcurl >= 7.45.0 needed for rtsp

### ISSUE THREAD

**Issue by Bhlowe** [atyenoria/janus-webrtc-gateway-docker#7]
If you can, could you upgrade libcurl to >=7.45 ? 

for the janus_streaming.c plugin, I get the following error:
JANUS_LOG(LOG_WARN, "RTSP digest authentication unsupported (needs libcurl >= 7.45.0)\n");

Thank you for the best janus docker.

**Comment by atyenoria** [comment]
@Bhlowe Okay,  I will do that. Thank you for the feedback!

**Comment by vovapolu** [comment]
Any progress on that issue? I have the same error and I need proper authentication provided by libcurl

**Comment by atyenoria** [comment]
How can I reproduce it?

**Comment by vovapolu** [comment]
@atyenoria I'm not sure that you can easily reproduce this issue. I can describe my case.

I'm using `streaming` plugin with a IP-camera that requires authorization. My config for streaming plugin looks like this:
```
camera1: {
	type = "rtsp"
	id = 1
	description = "Camera1"
	audio = false
	video = true
	videopt = 126
	videortpmap = "H264/90000"
	videofmtp = "profile-level-id=42e01f;packetization-mode=1"
	url = "rtsp://<camera-ip>:554/"
	rtsp_user = "admin"
	rtsp_pwd = "password"
}
```
With this config your container can't authenticate to the camera, because of the old version of `libcurl`. 

I've already fixed this issue for me building docker container on debian `stretch` instead of `jessie` as in your container. Debian `stretch` has newer version of `libcurl`. But I have completely rewritten docker image using instructions from the main repo https://github.com/meetecho/janus-gateway because I couldn't make all your additional dependencies work for `stretch` (probably I don't need them at all, I need only streaming plugin).

**Comment by Classsic** [comment]
@vovapolu can you share your Dockerfile? I get the same issue.

**Comment by vovapolu** [comment]
@Classsic Yeah, sure. https://gist.github.com/vovapolu/fcbb70d3c94d2618901449e518f43aaf
I've disabled all the plugins except streaming and haven't optimized size of the container yet. It copies janus configuration files from `conf` dir and web-interface files from `camera-streams` dir.

**Comment by Classsic** [comment]
Great, I will testit and give a feedback.
Thanks.
